version: "3.8"

services:
  outline-server:
    image: quay.io/outline/outline-server:latest
    container_name: outline-server
    restart: unless-stopped
    network_mode: "host"         # обязательно для работы WireGuard / Shadowsocks
    environment:
      - TZ=Europe/UTC 
    volumes:
      - ./outline-data:/opt/outline/persisted-state